name: "Manually: build the image"

on: workflow_dispatch

jobs:
  build_image:
    name: "build the image"
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/vpnhouse/*
    steps:
      - uses: actions/checkout@v2

      - name: Cleanup the ref name
        # turns "refs/heads/fix/this-and-that" into
        # the docker-tag-friendly "fix-this-and-that".
        run: echo "GITHUB_REF_SHORT=$(echo $GITHUB_REF | sed -e 's/refs\/heads\///' -e 's/\//-/')" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: vpnhouse/tunnel:${{ env.GITHUB_REF_SHORT }}
          build-args: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
